### ISSUE TITLE
Create - Add Details - Updating List attributes (Name or Extension) creates a new list which overwrites the existing list with a new CMQ_CODE.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#160]
Module: Create
Form: Add Details

1) Created and saved a new list (CMQ) . (Example: Name: TMELIST, Extesion : TME, etc)
2) In the Add Details, updated CMQ_NAME and saved the list second time. (E.g. TMELISTUPDATE)
3) System saved the list with a new name and generated a new CMQ_CODE.
4) The system overwrite the list created in step #1 with the list name in step #2 and also generated a new CMQ_CODE.

**Comment by vireshwali** [comment]
Technically this can be fixed but this should not be allowed now since my understanding is that we were doing the save only for the first time in create flow path. What the defect is asking for is to allow create to behave as update as well. Technically this should not be allowed. We probably should do something like this.....once we create the list and save it we should make the fields readonly. If the user wants to update the list they can use the update module.

If you want create to behave as update as well, do let me know and i will try to fix the save logic. But if you are inclined towards read only stuff once save is done then Leyla or Andrius need to handle it.

**Comment by zmeenakshi** [comment]
I agree. The Add Details should NOT allow user to update the details.

**Comment by zmeenakshi** [comment]
Leyla, please see Viresh comment and update accordingly.

**Comment by zmeenakshi** [comment]
Fixed.
