### ISSUE TITLE
Impact Assessment, Fix Table Alignment for Expanding Lists

### ISSUE THREAD

**Issue by acoughlin** [DBMS-Consulting/CQT2#164]
Module: Impact Assessment
Page: Impact Assessment

When data is added, Impact Assessment's Current(left) table and Target(right) table are uneven. 

![image](https://cloud.githubusercontent.com/assets/12534580/24250618/e84f9258-0fad-11e7-9640-b7a92dfae6b3.png)

Then, when we expand the lists, it gets worse.

![image](https://cloud.githubusercontent.com/assets/12534580/24250793/73f68528-0fae-11e7-90e3-c773c042fb48.png)

If there is a long list, you see the problem:

![image](https://cloud.githubusercontent.com/assets/12534580/24250879/b450de52-0fae-11e7-9d21-6c37bd74f0db.png)

Please correct it so that the two tables stay aligned at the top.

**Comment by acoughlin** [comment]
Also, adjust font size to match Relations page

**Comment by andmiel81** [comment]
please check this if it is still an issue.

**Comment by zmeenakshi** [comment]
1) When expanding term node, the window should expand (in length) a little more so that user can view at least 10 records  at a time.
2) Reduce the width of code, level and scope in the left panel and Expand Existing lists/SMQs
3) Reduce the width of code, level, category (1 char) i and weight (1 char) in the right panel and Expand Future lists/SMQs
4) Scope, category and weight should be read-only in CMQ_BASE_TARGET.CMQ_ALGORITHM ='N'.

![image](https://cloud.githubusercontent.com/assets/25993316/24440481/059b94ba-1472-11e7-8137-d1d466d969f5.png)

**Comment by andmiel81** [comment]
please check if this is fixed now.

Note:
 I have tried to further customize the width of code, level and scope, however, there is not easy way to do it. I have read in the forum, that it is due to the limitation of table rendering (datatables and treetables) of primefaces, especially when multi-row table header with colspans and rowspans are used.

**Comment by zmeenakshi** [comment]
Ok, looks better.
