### ISSUE TITLE
Copy: Errors displayed on performing Search action

### ISSUE THREAD

**Issue by CQTdev** [DBMS-Consulting/CQT2#314]
In Copy module, entered list name %_5% and clicked Search button. Please see the error messages in the screenshot.

![image](https://cloud.githubusercontent.com/assets/26054860/25738848/e5811400-319c-11e7-871d-d577b8e0b682.png)

**Comment by CQTdev** [comment]
In Update and Browse & Search modules also,searching list by %_5% is not displaying the expected lists, rather all lists are displayed in search results.

![image](https://cloud.githubusercontent.com/assets/26054860/25738983/736cd920-319d-11e7-866c-e994f0ea8141.png)

**Comment by andmiel81** [comment]
wildcards explained:
% matches 0, one or more of ANY character. 
_ matches any ONE character 


Thus the search result is rather correct.
And adding % wildcard is not needed because list name will be wrapped by % by default when doing the search.
if you have meant not to use _ as a wildcard, we should escape it.

Confirm the detailed usecases and let me know if we have to escape _ always, or to leave it as it is now.

**Comment by CQTdev** [comment]
Search Directions have been given to client in Release notes 1.0.8.

Directions for user to perform Search in UPDATE/COPY/BROWSE & SEARCH modules.
•	Lists with name containing 'word':  just using ‘word’ would be OK, or use '%word%'
•	List names ending with 'word': use '%word’
•	List names starting with 'word': use 'word%'
•	Search should not be performed using two wildcards together, like %_5% or %_TME%.
This will retrieve all lists in the database.
