### ISSUE TITLE
The warning for unsaved details does not move you to informative notes when you click Save

### ISSUE THREAD

**Issue by acoughlin** [DBMS-Consulting/CQT2#477]
Module: Create
Page: Details

Create a list on Add Details tab without saving it, moving to Add Informative Notes tab and then saving it,the current page is still in Add Details tab.

--Do not implement this yet, as we are unsure of whether this is working as intended or not.

**Comment by zmeenakshi** [comment]
SSUE: The form navigation is FIXED for Create -> Add Details, however rest of it is NOT working any more (on clicking Add Relations or Confirm tab after entering description in Add Informative Notes, the user is NOT navigated to Relations or Confirm respectively.)
Same thing happens when clicking the Next button upon entering Description, the system prompt for the unsaved changes but doesn't navigate to the next form.
The issue is coming in Add Relations also. The user is NOT navigated to Confirm tab on clicking the Confirm tab or Next button upon acknowledging the unsaved prompt.
