### ISSUE TITLE
Hierarchy Search for PT and LLT is VERY Slow/Pagination for the Pop-up

### ISSUE THREAD

**Issue by acoughlin** [DBMS-Consulting/CQT2#84]
Module: Update/Copy/Create
Page: Hierarchy Search

Searching for either one of these extensions takes 10+ seconds to return results. Other extensions are fine.

EDIT:

the number of PT's that get loaded onto the page starts to kill the application because it becomes very slow, so if it is possible, could we create some sort of page system to break up how many get populated at once?
Or maybe... more load as you scroll down, but don't necessarily all load at the same time

**Comment by vireshwali** [comment]
this is because there is to much data in the db.....for one I don't agree that we should allow search on just the level....Normal practice is to have atleast 3 characters to initiate the search.

Also we need ot fix the pagination on that popup first....after that i can paginate the fetch mechanism. Please assign this to Leyla to fix the pagination.

**Comment by acoughlin** [comment]
Hi Leyla, can you take on the pagination as Viresh says needs to be done?

**Comment by singhsg** [comment]
Please let me index first.  I wanted to understand the performance profile first *without* the indexing.

Thanks,
Sunil G. Singh
DBMS Consulting, Inc
singh@clinicalserver.com
+1-860-983-5848

**Comment by singhsg** [comment]
I will add indexes.
Thanks,
Sunil G. Singh
DBMS Consulting, Inc
+1-860-983-5848
singh@clinicalserver.com

**Comment by lsalim** [comment]
I will work on it
